name: Production Deployment
run-name: 'Deploy Production : ${{ github.event.head_commit.message }} / ${{ github.ref_name }}'
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    Prod-Unit-Tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'latest'
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 10

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run Unit Tests
              run: pnpm test:coverage
    Deploy-Production:
        if: github.event_name == 'push'
        needs: Prod-Unit-Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 10
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
